name: Codeowners merging
on:
  pull_request_target: { types: opened }
  issue_comment: { types: created }
  pull_request_review: { types: submitted }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Codeowners merge check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: orta/code-owner-self-merge@master
